services:
  web:
    image: python-scrcpy:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Web UI
      - "8000:8000"
    volumes:
      - scrcpy_adb_keys:/root/.android
      - ./static:/static
      - ./templates:/templates
      - ./user_prefs.json:/user_prefs.json
      - ./simplewebui.py:/simplewebui.py
    networks:
      - scrcpy_net
    depends_on:
      - mediamtx
    command: ["gunicorn", "--config", "/templates/gunicorn_config.py", "simplewebui:app"]

  mediamtx:
    build:
      context: .
      dockerfile: mediamtx.Dockerfile
    ports:
      - "8554:8554"  # RTSP
      - "8888:8888"  # API
      - "8889:8889"  # Metrics
      - "8189:8189/udp"
      - "8890:8890/udp"  # WebRTC
    volumes:
      - ./mediamtx_conf:/mediamtx_conf
    networks:
      - scrcpy_net
    restart: unless-stopped
    command: ["/mediamtx_conf/mediamtx.yml"]

networks:
  scrcpy_net:
    driver: bridge

volumes:
  scrcpy_adb_keys: